"use client";

import Link from "next/link";
import { useState } from "react";
import { Badge, Button, Callout, Card, Modal, SectionTitle, Toggle } from "@/components/ui";
import { cx } from "@/lib/format";
import { useStore } from "@/lib/store";

const FLOW = [
  { label: "Open MindEase", tone: "bg-info-100 border-info-300 text-info-900" },
  { label: "Privacy onboard", tone: "bg-mint-100 border-mint-300 text-mint-900" },
  { label: "Anonymous community", tone: "bg-pro-100 border-pro-300 text-pro-900" },
  { label: "Private journal", tone: "bg-info-100 border-info-300 text-info-900" },
  { label: "Support signal", tone: "bg-amber-100 border-amber-400 text-amber-900" },
  { label: "Opt-in counselling", tone: "bg-teal-100 border-teal-300 text-teal-900" },
  { label: "Counsellor alert", tone: "bg-pro-100 border-pro-300 text-pro-900" },
  { label: "Human review", tone: "bg-pro-100 border-pro-300 text-pro-900" },
  { label: "Support action", tone: "bg-mint-100 border-mint-300 text-mint-900" },
];

const STEPS = [
  {
    route: "/",
    say: "Before we ask a student for anything, we show them the promise.",
    notice: "Four privacy cards on the landing screen — nothing has been collected yet.",
  },
  {
    route: "/onboarding",
    say: "The identity is generated on the device. There is no profile to fill in, on purpose.",
    notice: "Counsellor sharing and journal sharing both start OFF.",
  },
  {
    route: "/student/community",
    say: "This is the peer-support feed. Notice the bar that never leaves the screen.",
    notice: "“Anonymous mode ON” persists in every community context.",
  },
  {
    route: "/student/community/new",
    say: "I'll write something the safety check will catch — try typing advice about stopping medication.",
    notice: "The composer offers a review before publishing rather than silently blocking.",
  },
  {
    route: "/student/home",
    say: "A check-in takes about ten seconds. Mood, what's affecting you, and that's it.",
    notice: "The home screen answers “what support can I use right now?”, not “here are your stats”.",
  },
  {
    route: "/student/journal/new",
    say: "The journal is deliberately a different place — quieter, blue, locked.",
    notice: "“Private to you” is on the screen the whole time you are writing.",
  },
  {
    route: "/student/journal/trends",
    say: "Four weeks of check-ins produce a pattern — and a supportive offer, not a score.",
    notice: "No number, no level, no “risk”. The word “depressed” never appears.",
  },
  {
    route: "/student/support/request",
    say: "Here is the consent screen. Every item starts off; the student ticks what they want to share.",
    notice: "The dialog lists what WILL and what will NOT be shared, side by side.",
  },
  {
    route: "/counsellor/alerts",
    say: "Now switch roles. The counsellor sees case IDs, levels and trends — never a name.",
    notice: "The alert generated by the student session is live in this queue.",
  },
  {
    route: "/counsellor/analytics",
    say: "And finally, institutional value with nobody identified.",
    notice: "Drag the threshold slider and watch small groups get suppressed.",
  },
];

const NOT_BUILT = [
  {
    what: "Real crisis phone numbers",
    why: "A wrong helpline number in a crisis is worse than none. Verified institutional contacts are configured at deployment.",
  },
  {
    what: "A backend",
    why: "Everything runs in this browser against localStorage, which stands in for the on-device storage model.",
  },
  {
    what: "A trained model",
    why: "The support indicator and the moderation classifier are transparent rule sets, so every signal can be read and argued with.",
  },
  {
    what: "Real authentication",
    why: "Role separation here is a route split; a deployment enforces it server-side. The counsellor settings screen says so explicitly.",
  },
];

export default function DemoPage() {
  const { ready, state, resetAll, setSimulate, toast } = useStore();
  const [confirmReset, setConfirmReset] = useState<null | "seeded" | "empty">(null);
  const [done, setDone] = useState<number[]>([]);

  const toggleDone = (i: number) =>
    setDone((d) => (d.includes(i) ? d.filter((x) => x !== i) : [...d, i]));

  return (
    <main id="main" className="mx-auto max-w-4xl px-5 py-10">
      <Link href="/" className="muted text-sm hover:underline">
        ← MindEase
      </Link>

      <header className="mt-4">
        <Badge tone="navy">Presenter&rsquo;s companion</Badge>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight text-navy-900">
          The end-to-end demo
        </h1>
        <p className="muted mt-2 max-w-2xl">
          Three to five minutes, one student, one counsellor. Every route below is
          clickable — you can drive the whole demo from this page and come back here between
          steps.
        </p>
      </header>

      {/* ----------------------------------------------------------- flow */}
      <section aria-labelledby="flow-heading" className="mt-8">
        <h2 id="flow-heading" className="sr-only">
          Demo flow
        </h2>
        <div className="no-scrollbar -mx-5 flex items-center gap-1.5 overflow-x-auto px-5 pb-2">
          {FLOW.map((f, i) => (
            <div key={f.label} className="flex shrink-0 items-center gap-1.5">
              <span
                className={cx(
                  "rounded-xl border px-3 py-2 text-center text-xs font-semibold whitespace-nowrap",
                  f.tone,
                )}
              >
                {f.label}
              </span>
              {i < FLOW.length - 1 ? (
                <span className="text-navy-300" aria-hidden>
                  →
                </span>
              ) : null}
            </div>
          ))}
        </div>
      </section>

      {/* ---------------------------------------------------------- steps */}
      <section aria-labelledby="steps-heading" className="mt-8">
        <SectionTitle
          title={<span id="steps-heading">Demo script</span>}
          subtitle="Tick them off as you go — the ticks are only in this tab."
        />
        <ol className="space-y-2.5">
          {STEPS.map((s, i) => {
            const complete = done.includes(i);
            return (
              <li
                key={s.route}
                className={cx(
                  "rounded-2xl border p-4 transition-colors",
                  complete ? "border-mint-200 bg-mint-50/50" : "border-navy-100 bg-white",
                )}
              >
                <div className="flex items-start gap-3.5">
                  <button
                    onClick={() => toggleDone(i)}
                    aria-pressed={complete}
                    aria-label={`Mark step ${i + 1} done`}
                    className={cx(
                      "mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-full border-2 text-sm font-semibold transition-colors",
                      complete
                        ? "border-mint-600 bg-mint-600 text-white"
                        : "border-navy-200 text-navy-700 hover:border-navy-400",
                    )}
                  >
                    {complete ? "✓" : i + 1}
                  </button>
                  <div className="min-w-0 flex-1">
                    <Link
                      href={s.route}
                      className="font-mono text-sm font-medium text-teal-800 hover:underline"
                    >
                      {s.route}
                    </Link>
                    <p className="mt-1.5 text-sm text-navy-800">
                      <span className="font-medium">Say:</span> {s.say}
                    </p>
                    <p className="muted mt-1 text-sm">
                      <span className="font-medium">They should notice:</span> {s.notice}
                    </p>
                  </div>
                </div>
              </li>
            );
          })}
        </ol>
      </section>

      {/* ---------------------------------------------------------- reset */}
      <section aria-labelledby="reset-heading" className="mt-8 grid gap-4 md:grid-cols-2">
        <Card className="p-4 sm:p-5">
          <h2 id="reset-heading" className="font-semibold text-navy-900">
            Reset for a fresh run
          </h2>
          <p className="muted mt-1 text-sm">
            Do this before you present, not during. Both options rebuild the campus around
            the student.
          </p>
          <div className="mt-4 space-y-3">
            <div className="rounded-xl border border-navy-100 p-3.5">
              <p className="text-sm font-medium text-navy-900">With demo history</p>
              <p className="muted mt-0.5 text-sm">
                Four weeks of check-ins, so the longitudinal support indicator has something
                real to be computed from. This is the one you want for the full story.
              </p>
              <Button size="sm" className="mt-2" onClick={() => setConfirmReset("seeded")}>
                Reset with history
              </Button>
            </div>
            <div className="rounded-xl border border-navy-100 p-3.5">
              <p className="text-sm font-medium text-navy-900">Empty account</p>
              <p className="muted mt-0.5 text-sm">
                No check-ins, no journal. Good for showing the genuine first-run empty
                states — but the support indicator will stay silent, correctly.
              </p>
              <Button size="sm" className="mt-2" onClick={() => setConfirmReset("empty")}>
                Reset to empty
              </Button>
            </div>
          </div>
        </Card>

        <Card className="p-4 sm:p-5">
          <h2 className="font-semibold text-navy-900">Failure states to show</h2>
          <p className="muted mt-1 text-sm">
            A frontend is judged on the failure path. Flip these and revisit the student
            screens.
          </p>
          <div className="mt-4 space-y-3">
            <div className="rounded-xl border border-navy-100 p-3.5">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="text-sm font-medium text-navy-900">AI unavailable</p>
                  <p className="muted mt-0.5 text-sm">
                    &ldquo;Support analysis is temporarily unavailable. Your private journal
                    remains available.&rdquo;
                  </p>
                </div>
                <Toggle
                  checked={ready && state.simulate.aiDown}
                  onChange={(v) => setSimulate("aiDown", v)}
                  label="Simulate AI unavailable"
                />
              </div>
            </div>
            <div className="rounded-xl border border-navy-100 p-3.5">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="text-sm font-medium text-navy-900">Offline</p>
                  <p className="muted mt-0.5 text-sm">
                    &ldquo;You&rsquo;re offline. Your private draft has been saved
                    locally.&rdquo;
                  </p>
                </div>
                <Toggle
                  checked={ready && state.simulate.offline}
                  onChange={(v) => setSimulate("offline", v)}
                  label="Simulate offline"
                />
              </div>
            </div>
          </div>
          <p className="muted mt-3 text-xs">
            Also worth showing: the empty community feed, the session lock (Settings →
            Profile → Lock now), and re-authentication before a destructive action.
          </p>
        </Card>
      </section>

      {/* --------------------------------------------------- not built */}
      <section aria-labelledby="scope-heading" className="mt-8">
        <SectionTitle
          title={<span id="scope-heading">What is deliberately not built</span>}
          subtitle="Say these out loud before a judge finds them."
        />
        <div className="grid gap-3 sm:grid-cols-2">
          {NOT_BUILT.map((n) => (
            <div key={n.what} className="rounded-2xl border border-navy-100 bg-white p-4">
              <p className="font-medium text-navy-900">{n.what}</p>
              <p className="muted mt-1 text-sm">{n.why}</p>
            </div>
          ))}
        </div>
      </section>

      <Callout tone="mint" icon="🎯" title="The line to land on" className="mt-6">
        One student went from anonymous onboarding to a counsellor taking a human decision,
        and at no point did the system learn who they were without being asked.
      </Callout>

      <Modal
        open={confirmReset !== null}
        onClose={() => setConfirmReset(null)}
        size="sm"
        title="Reset the demo?"
        description="This wipes the current session in this browser and rebuilds it."
        footer={
          <>
            <Button onClick={() => setConfirmReset(null)}>Cancel</Button>
            <Button
              tone="primary"
              onClick={() => {
                if (confirmReset) resetAll(confirmReset);
                setConfirmReset(null);
                setDone([]);
                toast("Demo reset", "success", "Start from the landing page.");
              }}
            >
              Reset
            </Button>
          </>
        }
      />
    </main>
  );
}
